"use Client"

import { Poppins } from "next/font/google";
import "./globals.css";
import MenuContextProvider from "./components/dashboard/MenuContextProvider";

const poppins = Poppins({ weight: ['400','500','700'], subsets: ["latin"] });

export const metadata = {
  title: "SALADMAKER",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-full min-h-screen ${poppins.className}`}>
        <MenuContextProvider>
          {children}
        </MenuContextProvider>
      </body>
    </html>
  );
}
