"use Client"

import { Poppins } from "next/font/google";
import "./globals.css";
import MenuContextProvider from "./components/dashboard/MenuContextProvider";
import Sidemenu from "./components/Sidemenu";

const poppins = Poppins({ weight: ['400','500','700'], subsets: ["latin"] });

export const metadata = {
  title: "SALADMAKER",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-full h-screen ${poppins.className} flex`}>
        <MenuContextProvider>
          <Sidemenu className="flex-grow"/>
          <main className="flex-grow">{children}</main>
        </MenuContextProvider>
      </body>
    </html>
  );
}
