import { Poppins } from "next/font/google";
import "./globals.css";
import Sidemenu from "./components/Sidemenu";

const poppins = Poppins({ weight: ['400','500','700'], subsets: ["latin"] });

export const metadata = {
  title: "SALADMAKER",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Sidemenu/>
          {children}
      </body>
    </html>
  );
}
